version: '3.3'

services:

  application:
    image:
      pdf-generator-image
    container_name: pdf-generator-container-1
    networks:
      - cloud
    ports:
      - 6799:6799
    depends_on:
      - database
      - redis
      - rabbitmq
      - producer
    environment:
      - "RABBITMQ_HOST=rabbitmq"
      - "RABBITMQ_PORT=5672"
      - "RABBITMQ_USERNAME=guest"
      - "RABBITMQ_PASSWORD=guest"
      - "SPRING_DB_URL=jdbc:postgresql://database:5432/app_db"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  database:
    image:
      postgres
    container_name: database
    networks:
      - cloud
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty007
    volumes:
      - pgdata:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  redis:
    image:
      redis
    container_name: redis-container
    networks:
      - cloud
    ports:
      - 6379:6379
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  rabbitmq:
    image:
      rabbitmq
    container_name: rabbitmq-container
    networks:
      - cloud
    ports:
      - 5672:5672
      - 15672:15672
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  producer:
    image:
      pdf-producer-image
    container_name: pdf-producer-container-1
    networks:
      - cloud
    ports:
      - 80:8080
    environment:
      - "RABBITMQ_HOST=rabbitmq"
      - "RABBITMQ_PORT=5672"
      - "RABBITMQ_USERNAME=guest"
      - "RABBITMQ_PASSWORD=guest"
      - "REDIS_HOST=redis"
      - "REDIS_PORT=6379"
      - "SPRING_DB_URL=jdbc:postgresql://database:5432/app_db"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
volumes:
  pgdata:
    external: true

networks:
  cloud:
    external: true
